# how the parameters are stored in the model?

All the model is stored in the following class attributes:

* ```A``` (numpy 2D array)
* ```pi``` (numpy array)
* ```LFMparams``` (dictionary)

* In `LFMparams` the parameters must be stored as they are, this is, without transformations.
* The function `pack_params` allows you to convert the dictionary `LFMparams` to a flattened array and, in addition to that, it applies the `log` operation over the parameters that are constrained to be positive.
* Conversely, The function `unpack_params` allows you to convert an array containing the parameters to a dictionary and it applies the `exp` operation to the must-be-positive parameters.

## Output of the current experiments related with emission parameters estimation.

Reset of emission hyperparameters.

In [ ]:
parameters : {'spring': array([[ 0.01315013],
       [ 0.63110198],
       [ 1.6302133 ]]), 'lengthscales': array([[  3.45497632e-20],
       [  2.44856958e-01],
       [  1.04295485e-03]]), 'sensi': array([[[ 39.26288376]],

       [[  0.30728971]],

       [[-11.54918141]]]), 'noise_var': 0.0, 'damper': array([[  2.94533092e+42],
       [  1.89775994e+00],
       [  1.06351696e+03]])}

Without reset

In [ ]:
parameters : {'spring': array([[  1.37490185e+33],
       [  5.29176013e-04],
       [  1.32213908e-04]]), 'lengthscales': array([[  1.24131748e+05],
       [  2.46286856e+04],
       [  2.83785822e-05]]), 'sensi': array([[[-16.7109375 ]],

       [[ 45.14575195]],

       [[ 18.20727539]]]), 'noise_var': 1.41140515155821e-07, 'damper': array([[  5.53253881e-69],
       [  1.39116075e-06],
       [  4.03789267e+03]])}

## INTERESTING: with a random initilization of the emission parameters I got the following result

In [ ]:
BEFORE {'spring': array([[ 0.00738016],
       [ 0.62222845],
       [ 0.20695498]]), 'lengthscales': array([[ 0.96840867],
       [ 0.24932085],
       [ 0.26036316]]), 'sensi': array([[[-2.8630928 ]],

       [[-0.10335482]],

       [[ 0.92347484]]]), 'noise_var': 100.0, 'damper': array([[ 1.70143305],
       [ 1.84927803],
       [ 0.99086296]])}
===============
CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
iterations: 1
===============
CURRENT VALUE OF EMISSION PARAMS: 
{'spring': array([[  3.00722339e+00],
       [  1.41117184e+00],
       [  6.48250443e-06]]), 'lengthscales': array([[  9.72668640e+00],
       [  7.51900430e+00],
       [  7.80435418e-04]]), 'sensi': array([[[-0.87095605]],

       [[-1.07240969]],

       [[ 8.52214177]]]), 'noise_var': 0.00051199915988875226, 'damper': array([[ 0.98212925],
       [ 3.66596507],
       [ 2.88231836]])}
iter:  44 , L(model|O) = 20620.4695285 , L(model_new|O) = 20620.4696096 , converging = True

This result seems to be a fairly good estimation for the emission parameters taking into account that they were initialized randomly. Except for the spring constant for the third output. The whole EM algorithm finished without errors giving the following estimation for $s$ and $A$.

In [ ]:
[ 0.37246972  0.57436305  0.05316723]
[[  1.92023284e-01   8.07976435e-01   2.80322597e-07]
 [  5.49872036e-01   4.38945299e-01   1.11826644e-02]
 [  1.24152441e-14   1.00000000e+00   7.62508508e-46]]

Actual parameters:

In [ ]:
initial state distribution [ 0.3  0.3  0.4]
hidden state transition matrix
[[ 0.1  0.5  0.4]
 [ 0.6  0.1  0.3]
 [ 0.4  0.5  0.1]]

Notice that the last value state of the model (Third LFM) is kind of eliminated in the inference process. Notice that 2 lfm has a spring/damper of 1/3 and the 3 lfm has a spring/damper of 5/6.